### ISSUE TITLE
Staking Dashboard for SNOW

### ISSUE THREAD

**Issue by ioannist** [web3labs/ice-substrate#150]
### Application Type
Please check one below.
- [ X] DEV & ECOSYSTEM TOOLS

**Subcategory:**
Please check all which apply.
- [X ] Other (Staking Dashboard)

### Team Introduction
My name is Ioannis and I am the head of the team. We specialize in creating and running staking dashboards that offer collator performance statistics, personal staking metrics (per delegator, per collator), and chain analytics. Examples include https://stakeglmr.com, https://stakebnc.com, https://staketur.com, https://stakemovr.com, https://stakeztg.com, etc with a combined user base of 100K+. Our goal is to enhance the staking experience for every major parachain in Dotsama. We run our own indexing backend in AWS so we don't have to rely on 3rd party solutions.
https://stakebaby.com

### Grant Request Amount
- Running a full-featured version of stakeicz would incur $200-$400 in AWS costs monthly (using reserved capacity discounts), based on tx volume. We also need 1-2 developer days per month for maintenance. Since our costs are monthly and over the long term, we either make a monthly payment agreement in fiat terms or the team agrees to back our collator in the active set. If neither of these is an option, we can also discuss a one-time amount but this would increase the risk on our side.

### Project Description
- We have already delivered this project for other parachains so it's best to check out the live versions. You can check out collator metrics at https://satkeglmr.com . Don't forget to click on the small lens in the last column.
- You can try the personal staking dashboard at https://stakeglmr.com/dashboard/dash-staking . Use this address if you want to load a lot of data: 0xF21cDd2f90c4D450BD27E01a3453bF346e6b4958
- We can also enable staking extrinsics in your dashboard (especially useful if you don't have your own staking interface) like we did in https://staketur.com/dashboard/dash-staking

### Milestone Duration
- 3 months
- Full website with all agreed functionalities delivered

**Comment by sos0** [comment]
Hi, we're letting you know that we've received your application and are undergoing discussion. We'll be posting questions for you, so you can keep an eye out here. Thanks for your patience.

**Comment by mohamedelshami** [comment]
Thank you for your application. 

SNOW is currently on PoA, there is no staking. This proposal won't be applicable at this point.

**Comment by ioannist** [comment]
Every network that we worked with was PoA before switching to the staking pallet. In all cases but one, we worked on this before they went PoS, so that's normal. We need a couple of months' heads-up to set it up and it makes sense to be operational from day 1 of the staking pallet.

**Comment by mohamedelshami** [comment]
Thanks, @ioannist.

We are likely going the same path of switching from PoA, however, we would like to prioritize other development at this stage. I would suggest closing this application for now and reopening it once we have clear timelines for the transition to PoS.
