### ISSUE TITLE
Iced Finance

### ISSUE THREAD

**Issue by 0xweb3builder** [web3labs/ice-substrate#157]
### Application Type
Please check one below.
- [x] DEV & ECOSYSTEM TOOLS
- [ ] COMMUNITY

**Subcategory:**
Please check all which apply.
- [ ] BTP
- [ ] DApp bounty
- [x] DeFi
- [ ] Gaming
- [ ] NFT
- [ ] Social good
- [x] DAO
- [ ] DID
- [ ] Cross-chain
- [ ] Other (Please specify)

### **Team Introduction**
- Who is the main liaison? Who’s working on this project as which role, and what experiences do they have?
  Main liaison will be Oleg.
  Oleg will work on this project as PM role.
  Dev team has developed lots of successful "defi lending & swap protocols & NFT marketplaces" including venus protocol.

### Grant Request Amount
- How much would this project need? We'd love to see details of your estimation of this project as well as the projected fund distribution and schedule for your team.
  This project will need `$200k` grant fund.
  Details of project estimation and fund distribution as well as schedule will be provided in doc.

### **Project Description**
- Here’s a [PRD Template](https://www.notion.so/Iced-Finance-08bdc8ffa79d4da8abd5c99656b978a4) for your convenience. Getting these requirements filled out will not only help your project toward a vision, but help us understand what value it can bring for the community.

#### Context

*Give a quick 1-2 line summary of the project to orient your readers.*

Lending Protocol.

A comprehensive decentralized-finance-based lending system to the ICE Chain.

#### Goals & Key Performance Indicators

*What are you hoping to achieve with this project? How will you know once you've gotten there?*

Money Markets is a one-stop-shop DeFi platform for lenders and borrowers that also includes AMM. Iced Finance is Money Markets. By utilizing ICD tokens, the community is able to:
(1) create a secure lending platform where lenders receive a compounded interest rate paid per block while borrowers pay interest on the cryptocurrency borrowed;
(2) provide liquidity, which contributes to the ecosystem's continuation and sustainability;
(3) govern select protocol features that support flexibility and community ownership;
By retaining the platform's governance via voting, the community improves it.

At a product launch, we will build infrastructure to handle up to millions of users and $10b tvl.

Our dev team developed venus protocol in BSC network, which was #1 defi lending platform with $10b tvl last year.

We will develop and build the same infra and architecture.

After service launch, we will be responsible for some period based on contracts, so it will not be a problem.

- Test levels and types
    - Levels: System/Integration test (Developer/Tester)
    - Functionality testing (Requirement-Based, Business-Based)
    - User Interface testing (Visual-checking)
    - Regression testing (Requirement-Based, Business-Based)

#### Constraints

*What limitations will you need to consider when building this product?*

Problems:

The blockchain is decentralized Finance has resulted in a tremendous amount of variation in the crypto-financial sphere. For new users, this might be incredibly intimidating. The Defi space must be new-user pleasant and secure throughout the network for the paradigm to be widely adopted. A borrower must offer credit or verifiable income to a lender in conventional financial lending systems before funds are considered. Iced Finance promises to alleviate this friction in the conventional lending system by allowing digital assets and cryptocurrencies to be pledged as collateral and earn interest.

#### Assumptions

*What assumptions are you making about your audience?*

Models and Solutions:

Defi is a borderless financial system that seeks to eliminate inefficiencies in the global financial system. In order to keep the network safe, Iced Finance has updated the Defi paradigm to enable user-supplied liquidity. The native token will be more reliable and safer as more users and liquidity providers join in. When a user provides liquidity to a pool, they become a liquidity provider (LP), and their token may be used for lending/borrowing on the blockchain or compounding to earn more interest. Due to the nature of this borderless system, it is a worldwide upgrade of Finance, enabling anybody to borrow funds, as opposed to the old system, which now excludes many nations and peoples. Furthermore, Iced Finance consumers would not have to be concerned about centralized institutions attempting to manipulate their money.

Iced Finance isn't the first decentralized financial platform to try to combine conventional lending with blockchain technology. Iced Finance benefits from the lessons learned from previous initiatives, resulting in a much better platform. Iced Finance will be the first ice lending protocol in order to earn high a APY returns and enhances ICD price/volume while also enabling them to borrow and supply assets using smart contracts.

We are targeting people and investors who are interested in defi borrow and lending, and familiar to crypto.

In general, ICE/SNOW users will use Iced Finance.

#### Dependencies

*In order to do this project, what else must be true? What does this project rely on?* 

Architecture of the system:

When consumers link to tokens through the lending platform, they must first connect to an underlying asset. The native tokens' monetary values are related to the items held as collateral. Because of the cryptocurrency's nature. The collateral values are derived in real-time from market rates utilizing the market price update tape recorder.

BAND will be the best oracle solution to use.

### **Milestone Duration**
- Which of the following describes your milestone? 1 month / 3 month / 6 month
    3 months milestone for `Phase 1 - Phase 3`
- What are the deliverables for this milestone duration?
  - Phase 1
    - Whitepaper and Landing Page Introduction (Phase1)
  - Phase 2
    - Iced Finance Testnet Lending App Launch
  - Phase 3
    - ICD to be listed on coinmarketcap
    - Iced Loans to be launched on the Mainnet

**Comment by mohamedelshami** [comment]
Thank you for your application.

We have some questions/comments:

- Please scope this down to smaller milestones to something tangible. We'd like to see some clarity.
- Venus Protocol is a well done defi app on Binance and looks clean, but it seems like this is EVM and could be easily portable. Can you describe the development effort in a bit more detail? 
- Can you break down your budget? 3 months milestone sounds like a much smaller scope than the budget.
- It's not easy to cross-check your involvement with Venus Protocol. How can we confirm this?
- Do you have design mock-ups for your product?

**Comment by mohamedelshami** [comment]
@0xweb3builder 

Given that there have been 2 weeks with no response, I'm going to close this application. Please feel free to reopen when you're ready to provide more details.
